"""empty message

Revision ID: c57d0a1b54ba
Revises: e35b30e6aaaf
Create Date: 2022-05-06 17:37:50.673398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c57d0a1b54ba'
down_revision = 'e35b30e6aaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_planet')
    op.add_column('favorite', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite', 'planet', ['planet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'planet_id')
    op.create_table('favorite_planet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['people.id'], name='favorite_planet_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_planet_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
